apps/authentication/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from apps.authentication import views

app_name = "authentication"

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(
        template_name="authentication/login.html"
    ), name="login"),
    path("diverge", views.diverge, name="diverge"),
]

apps/core/urls.py
from django.urls import path

from apps.core import views

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
]

apps/crew/urls.py
from django.urls import path
from apps.crew import views

app_name = "crew"

urlpatterns = [
    path("index", views.index, name="index"),
]

apps/supervisor/urls.py
from django.urls import path
from apps.supervisor import views

app_name = "supervisor"

urlpatterns = [
    path("crews", views.crews, name="crews"),
    path("register_crew", views.register_crew, name="register_crew"),
]

apps/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("apps.core.urls")),
    path("authentication/", include("apps.authentication.urls")),
    path("supervisor/", include("apps.supervisor.urls")),
    path("crew/", include("apps.crew.urls")),
    path('admin/', admin.site.urls),
]

apps/authentication/models.py
from django.contrib.auth.models import (
    BaseUserManager,
    AbstractBaseUser,
)
from django.db import models
from django.utils import timezone


# Create your models here.


class StaffManager(BaseUserManager):
    def create_user(self, username, last_name, first_name, password=None):
        if not username:
            raise ValueError("usernameは必須です。")
        if not last_name or not first_name:
            raise ValueError("名前の記入は必須です。")

        staff = self.model(
            username=username,
            last_name=last_name,
            first_name=first_name,
        )

        staff.set_password(password)
        staff.save(using=self._db)
        return staff

    def create_superuser(self, username, last_name, first_name, password):
        staff = self.create_user(
            username=username,
            first_name=first_name,
            last_name=last_name,
            password=password,
        )
        staff.is_admin = True
        staff.save(using=self._db)
        return staff


class Staff(AbstractBaseUser):
    id = models.BigAutoField(primary_key=True)
    username = models.CharField("username", unique=True, max_length=24, db_index=True)
    last_name = models.CharField("名前　姓（カナ）", max_length=24, db_index=True)
    first_name = models.CharField("名前　名（カナ）", max_length=24, db_index=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField("作成日時", default=timezone.now)
    updated_at = models.DateTimeField("更新日時", auto_now=True)


class Crew(Staff):
    is_admin = models.BooleanField(default=False)

    object = StaffManager()

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["last_name", "first_name"]

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin


class SuperVisor(Staff):
    is_admin = models.BooleanField(default=True)

    object = StaffManager()

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["last_name", "first_name"]

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

apps/authentication/forms.py
from django import forms
import zenhan
from apps.authentication.models import Crew
from apps.authentication.strings import Strings


class CrewRegisterForm(forms.ModelForm):
    class Meta:
        model = Crew
        fields = ("username", "last_name", "first_name")

    def clean_username(self):
        username = self.cleaned_data.get("username")
        if not Strings.is_alphabet(username):
            raise forms.ValidationError("入力できるのはアルファベット、数字、ハイフン、アンダーバー、半角スペースのみです。")
        return username

    def clean_last_name(self):
        last_name = self.cleaned_data.get("last_name")
        if not Strings.is_kana(last_name):
            raise forms.ValidationError("入力できるのはカタカナのみです。")
        return zenhan.h2z(last_name)

    def clean_first_name(self):
        first_name = self.cleaned_data.get("first_name")
        if not Strings.is_kana(first_name):
            raise forms.ValidationError("入力できるのはカタカナのみです。")
        return zenhan.h2z(first_name)

apps/authentication/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse as url_reverse
from django.contrib.auth.views import LoginView
from apps.authentication.models import Crew, SuperVisor
from django.urls import reverse as url_reverse


# Create your views here.

def diverge(request):
    if isinstance(request.user, SuperVisor):
        return HttpResponseRedirect(url_reverse("supervisor:crews"))

    if isinstance(request.user, Crew):
        return HttpResponseRedirect(url_reverse("crew:index"))
    return HttpResponse("無所属！")



def index(request):
    return HttpResponse("hello!")

apps/core/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse as url_reverse


# Create your views here.

def index(request):
    return HttpResponseRedirect(url_reverse("authentication:login"))

apps/crew/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return HttpResponse("crewだよ！")

apps/supervisor/views.py
from django.shortcuts import render

from apps.authentication.decorators import check_staff_type
from apps.authentication.models import Crew, SuperVisor
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from apps.authentication.forms import CrewRegisterForm
from django.http import HttpResponseRedirect
from django.urls import reverse as url_reverse
from apps.authentication.strings import randstr
from apps.core.utils import union_dict


# Create your views here.
def __generate_initial_password():
    return randstr(8)


@login_required
@check_staff_type(["SuperVisor", ])
@require_http_methods(["GET", "POST"])
def crews(request):
    crews = Crew.object.all()
    return render(request, "supervisor/crew/crews.html", {
        "crews": crews
    })


@login_required
@check_staff_type(["SuperVisor", ])
@require_http_methods(["GET", "POST"])
def register_crew(request):
    if request.method == "GET":
        return render(request, "supervisor/crew/register_crew.html", {
            "form": CrewRegisterForm()
        })
    form = CrewRegisterForm(request.POST)
    if not form.is_valid():
        return render(request, "supervisor/crew/register_crew.html", {
            "form": form
        }, status=400)
    raw_password = __generate_initial_password()
    crew = SuperVisor.object.create_user(**union_dict(form.cleaned_data, {"password": raw_password}))
    return render(request, "supervisor/crew/register_display.html", {
        "crew": crew,
        "raw_password": raw_password,
    })

templates/authentication/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
          integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
</head>
<body>
<div class="container">
    {% block main %}{% endblock %}
</div>
</body>

templates/authentication/login.html
{% extends "authentication/base.html" %}

{% block main %}

{% if form.errors %}
<p>ユーザー名とパスワードが違います。もう一度記入ください。</p>
{% endif %}

<form method="post" action="{% url 'authentication:login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>


{% endblock %}

templates/supervisor/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
          integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <h2>管理者画面</h2>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <ul class="nav">
            <li class="nav-item ">
                <a class="nav-link active" href="{% url 'supervisor:crews' %}">Top</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'supervisor:register_crew' %}">クルー登録</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="">ログアウト</a>
            </li>
        </ul>
    </nav>
    {% block main %}{% endblock %}
</div>
</body>
</html>

templates/supervisor/crew/crews.html
{% extends "supervisor/base.html" %}
{% load widget_tweaks %}
{% block title %}クルー一覧{% endblock %}
{% block main %}
 <br><h2>クルー一覧画面</h2><br>
<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">username</th>
        <th scope="col">名前　姓</th>
        <th scope="col">名前　名</th>
        <th scope="col">登録情報編集</th>
        <th scope="col">休憩時間編集</th>
    </tr>
    </thead>
    <tbody>
    {% for crew in crews %}
    <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ crew.username }}</td>
        <td>{{ crew.last_name }}</td>
        <td>{{ crew.first_name }}</td>
        <td><a href="" >ユーザー情報</a></td>
        <td><a href="">編集</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

templates/supervisor/crew/register_crew.html
{% extends "supervisor/base.html" %}
{% load widget_tweaks %}
{% block title %}クルーの登録{% endblock %}
{% block main %}
<br><h2>クルーの登録</h2><br>
<form action="{% url 'supervisor:register_crew' %}" method="post">
    {% csrf_token %}
    <h3>登録情報</h3>
    <div class="form-group">
        <label>{{ form.username.label }}</label><br>
        {% render_field form.username placeholder="yoshida_naoya" %}
        <p>{{ form.num.errors }}</p>
    </div>
    <div class="form-group">
        <label>{{ form.last_name.label }}</label><br>
        {% render_field form.last_name placeholder="ヨシダ" %}
        <p>{{ form.last_name.errors }}</p>
    </div>
    <div class="form-group">
        <label>{{ form.first_name.label }}</label><br>
        {% render_field form.first_name placeholder="ナオヤ" %}
        <p>{{ form.first_name.errors }}</p>
    </div>
    <button type="submit" class="btn btn-primary">登録する</button>
</form><br>
{% endblock %}

templates/supervisor/crew/register_display.html
{% extends "supervisor/base.html" %}
{% load widget_tweaks %}
{% block title %}クルーの登録情報{% endblock %}
{% block main %}
<br><h2>クルーの登録情報</h2><br>
<h3>登録したクルー</h3>
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">登録情報</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>username</td>
        <td>{{ crew.username }}</td>
    </tr>
    <tr>
        <td>名前　姓（カナ）</td>
        <td>{{ crew.last_name }}</td>
    </tr>
    <tr>
        <td>名前　名（カナ）</td>
        <td>{{ crew.first_name }}</td>
    </tr>
    <tr>
        <td>初期パスワード</td>
        <td>{{ raw_password }}</td>
    </tr>
    </tbody>
</table>
{% endblock %}

templates/supervisor/index.html
{% extend{% extends "admin/base.html" %}
{% load widget_tweaks %}
{% block title %}クルー一覧{% endblock %}
{% block main %}
 <br><h2>クルー一覧画面</h2><br>
<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">username</th>
        <th scope="col">名前　姓</th>
        <th scope="col">名前　名</th>
        <th scope="col">登録情報編集</th>
        <th scope="col">休憩時間編集</th>
    </tr>
    </thead>
    <tbody>
    {% for crew in crews %}
    <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ crew.username }}</td>
        <td>{{ crew.last_name }}</td>
        <td>{{ crew.first_name }}</td>
        <td><a href="" >ユーザー情報</a></td>
        <td><a href="{% url "admin:crew_break_logs" crew.id %}">編集</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}